### PR TITLE
update cache database from sqlite3 to postgres

### PR DESCRIPTION
**Pull request by SajidZakaria**
Hi. I have migrated the cache database to heroku. For now, it is functional, but has a loophole(a specific contest might be published more than once. but I'll fix that over time).

### CODE REVIEW

**Comment by ParsaAlizadeh** [comment]
Wow! I didn't notice heroku removed their table limit.

What is `HEROKU_POSTGRESQL_BLUE_URL`? Is this supposed to be the same as `DATABASE_URL`? or a new database?

There is still 10'000 row limit, and I see that you truncate `rating_change` on every restart. This cause the duplicate publish. It is the only way `cache_system2.is_newly_finished_without_rating_changes` checks to stop publishing twice.

Instead of truncating `rating_changes`, I am thinking about another trick, to save rating changes of handles in user database and ignore everyone else. I guess there is a very easy (and messy, I know) way if `HEROKU_POSTGRESQL_BLUE_URL` is equal to `DATABASE_URL`. We can add a `WHERE` in `cache_db_conn.save_rating_changes` to filter handles that are available in `user_handle`.

Also I think it is good to have a manual trigger like `;cache truncate`.

**Comment by SajidZakaria** [comment]
Hi. So here are some things to clear out:
1. I have imitated the double database system of the actual source, so `HEROKU_POSTGRESQL_BLUE_URL` is the second database, which connects to the cache system.
2. The local DB cache system has one flaw, it gets erased every now and then, thus publishing contests ranking more than once. That's why I thought of making the cache database non-resetting by porting to Heroku Postgres. But the problem remains, that the maximum number of rows(10000) gets exceeded very often, which will cause the database to halt. For that, I've done an automated reset after every specific period. This isn't obviously the solution, and I think we'd have to come with something better, which won't be too hard to find. But as of now, the database is completely functional on Heroku Postgres.
3. There's probably a same table name in both cacheDB and userDB, for that I thought we can't use them in the same database.

**Comment by ParsaAlizadeh** [comment]
What is a suitable solution here? What is worth preserving or losing?

As I see in our server, people rarely use commands related to some sort of caching rating change.
Disabling this feature and just saving published contest ids seems fine to me.

**Comment by SajidZakaria** [comment]
Yes I thought so too. Actually, in our server the rating publishing thing is very important. If we can do it in other means that would be great. I also think keeping the contest id is a better way.

**Comment by ParsaAlizadeh** [comment]
> If we can do it in other means that would be great.

I am not sure I get what you are saying. Can you provide an example?

I have a simple way. I can change `(contest_id, handle)` to just `(contest_id)`, so it stores 1 row per contest.
https://github.com/SajidZakaria/TLE/blob/hoi/tle/util/db/cache_db_conn.py#L169

But I feel this is not the way you want it.

**Comment by SajidZakaria** [comment]
No no, that is perfect. This would get rid of the unnecessary stuff and also fix the multiple publish issue.

**Comment by ParsaAlizadeh** [comment]
I've done some changes in [another branch](https://github.com/ParsaAlizadeh/TLE/tree/cache). I am going to test it for a while, and then merge this PR.

**Comment by SajidZakaria** [comment]
Awesome. Looking forward to this exciting update.

**Pull request merged**
